package com.softtech.dsl;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;

import com.softtech.dsl.codegenerators.ApplicationCodeGenerator;
import com.softtech.dsl.model.definitions.*;

public class Main {

	public static void main(String[] args) {
		Application crmApp = buildCrmApp();
		
		/*
		try {
			//new ApplicationCodeGenerator(crmApp, "c:\\AutoGenerated").Generate();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}*/
	}

	private static Application buildCrmApp() {
		
		HashMap<String,Entity> custChildren=new HashMap<String,Entity>();
		custChildren.put( "CustomerId", PrimitiveTypes.StringTypeEntity);
		custChildren.put( "Name", PrimitiveTypes.StringTypeEntity);
		custChildren.put( "Surname", PrimitiveTypes.StringTypeEntity);
		custChildren.put( "Address", PrimitiveTypes.StringTypeEntity);
		Entity custFeature = new Entity(
				new Classification("Customer", "Customer", "Crm", new HashSet<String> (Arrays.asList( "Customer" ))),
                custChildren);

		HashMap<String,Entity> orderChildren=new HashMap<String,Entity>();
		orderChildren.put( "OrderId", PrimitiveTypes.StringTypeEntity );
		orderChildren.put( "Product", PrimitiveTypes.StringTypeEntity );
		orderChildren.put( "Address", PrimitiveTypes.StringTypeEntity );
            
		Entity orderFeature = new Entity(new Classification("Order", "Order", "Crm", new HashSet<String> (Arrays.asList( "Customer" ))),
                orderChildren);

        return new Application(new Classification("Crm-Java", "Customer Relationship Management","CRM",new HashSet<String> (Arrays.asList("Crm","Customer" ))),
        		new ArrayList<Entity> (Arrays.asList(custFeature,orderFeature)));
		
		
	}

}
